language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: Q9AHNhmBTiE01Pn4Ed051nEdJAvCGMwGqX1aXEvQirJmT1db4uGElK+ncDmbo0Ltwt66UfCc3/3GKkf9ZDNlhHQOno6b+qGJ4lelybztlBV+zoZV1ckUS3lILMSaNj6P2e7xW4r1nZuUCU0BigUNCmSfRRFYNxWv+CsFh4G0a1oUbeVaxkGEKmSCOvyzvNp86+QKjyDWQbskaUnCJexOschSkcNMxs9Hh0WrPZ4kCezJ45xkUpNkI+RU9EZNFgpNUTdkHxn1QplwI9OBFxO1kEGCCdgL4CFPjeKi0A6+kZCVvB5TJzNmvo2TIC14/dgmtHOJsIvUnVYZRKlKWaa7fSzZIMsn1o9stUWK4R+zhNbcwHqLlzUv7texZQ3SAF626FP8liIGiQ35I7mHkHeANo7mX/0m7DFDTbVBh8JOUB/IoWHVSrIdcjnZ+gprC98gpuy0WcqmuOOhoED2Bs4FwqLpHDBfKLomJUG3sd2xs06iyGNF96LH90DDXe1apDTYO/WsUxTP5cMDm9e8EZqXMehicdf6VCBGsTtIDaVCA3B3b7tU09kqkLeDLd1PjXnB2fIYudB5ViY5VPlrf1wEkSL95IndM6/sMHEa1LkAcmIfgkE7WofIBD1xiGSy8yCwz5L/sQPTWeRMNFCvOhBCIaKbPHF6crENiHy13+aKvOM=
notifications:
  slack:
    secure: OCmWtoaT+UEkt+bs6taeJU7Pjs5abuT9gS9E784p7zmkrb1dcYByIA9x2JxNxscArd/TLe++YuZmyyHcb0/AP67rzYwUOJ0CI2YfXgs2QyK71Hfd3x8dJRbkV0hyqB1f8RyoXrke9AAyTr3MxUjtwXcn16PVceu33uYxjs73dEYQxWDMu0rwYB2kVZO0si/YZ3QlkTT9Woc47HcFAbVt2su6Y2yapkqHfT7mcCgW/O+ZLbsnQehwEn2ZsNjiDVPSoN3Q8zy4UuGjayktRh4GK5iNXcDnlDwgiG3XCz3E9qaTEnJp7QsySVCL/PBE/9c5j12geYV8PVfsvnOemIqMCpF4vXgWoozalDwSSLuiOkvT7pyuF43i2t+3RHLW+k1wuxLBSEY8j8V7JEm+lpoheVttoCSzG1zQqlBPVO+WybxMO1IZDsVqOHcoc4jgQqnSoPtUAay1Yx8f/Hl4d0e1hx+tr4vs20VQXCaLssm6DphpHuSBbuaPjDQmsMqA/VyU2n2bIdoNQQHgo4WgRVAX117FSF0jYvKqPbOm2IDjjOpZPU6H+BQe0Gm4D8hUR1dkTiaJ4nCbWBxD6Fm8UDXYeRXxmlu04e6hrKW74WytSPDAp+QzjKn3SNWpn+fwkICUtJyaloY1mgS8IGxTH8BXvY6oPnz7rv6puXA3eJHZqD8=
