language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: jGMC6vnV80nLMNv7RZ+oZNRIb4edY3uY8NH6VV/PQp00uLo08xwOYYlgvDiuYvxRPRoU35Nwh0PJAOk2m2Jrq5miBLh7VinIdXva+hcRgCBycAaIw8tLQqu9/7wOTqqpbxQENxllPB2gdvWLKgJ6o9JwofbQVHLxRkh9iM0salPH1uF5N5WecHkxkiwXp4ySy1Uo78by+VUzjoH+29BDwumrnuBkUQ31A8wogI2dhAzGcw8hVcPkdobeEoyOqI12+POPDeurctA0pTSn8pgtsudPaWeVPjN4J0yQ8PAfE6Gue1hlHG/o1tMxMgtjo9ScVLH2MolYcTRxwP6R3ffbHjUzvaUkdvwn+iQVokNxshKd4S4jOV++U6puTqMnqunHnNRZhf4Lx39KXb/fS9BsoufmrNoYtidKceinuYjwkrB4VURUwrt9jfL2hWZ8uty9ixN5qAnuhHgK+k2Ff3cfNEyFmsGjyiaIN6cRgQzbc2MeGWqBHg+/eFvg8aRCmvtS3YWCpLlZWzGXlllBRYx0aUvmNsg/aOpYCuybz/po7ebNHYdEHD2xqVtSYc+S7NYGpta6k228PGNCEkDcklpJtl/2hdvaORpOWvGs/O2Wk614VboFm5Vk3no0f1lKuuCoOzW5LkBLgg0/tyV94vUlCJsMb4J/4ep1XQGbiUJdcGs=
