language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: cSx5UEB2bjak5lLAwpqazKnR3tcPv8AEXsIH3UbAXL0/kowa9nmh8lzH+3SvHJB/M/N1zkgSxaSGagfi8I7ff3BLDa3oJWEQ4Grh/z6LSELajcXIK5vEpi/3F6zxs7Pi/uYXLnWYTW836Ss82ulvZ3qrVYRcu5ICHsXxeY2N4Cnbrn1w5HYDaQ6oTQSILY8IAqn8uhpLjl7vQZyFlPRh75BDT6REtx3cGvtjjryoLSVSkH+v02/9TVsiJUfw6PUhPZuBEl8w8tIxhE9PUc2cfdzLw/pfgjqUipB17IbCFM8cUFdEoaLX8YltENE7rx9nHpQjiAHeWoyNmQTPmh6adSQHa4FtjsAVimb+we97xkvHA3UxtL4s0M/P6Z1o0aDNlneQRQ0hkV4RDlrlK2AgbQpjVffrEYBQeWX1dkr/ohbrB7O1Os9N+UkxstB/Mu/xmhCzgsKFmSIOkoWmmtnLYux0e2nubWyLx7DA2Q5EdlC62f58Je8Jy48e5n3R26RqSVIVUf63BsQ9TriGOXIxp+taAzFgJAvGrC5L/Z4zcgJY4tCzAF2p20OFviXlXNTfbegUjnSPGMKl0B9fSBe0eBkTmYx6lmrZZ1jvL4YgqCcKPGR1TTNQ2ttVayMcz4F0rjMcTaQ7PqVM1AGhd9AwtsnbuOjWBJtZkj6FueQAJqg=
notifications:
  slack:
    secure: oRMm/BU3t6oJGn1GbekvdCZYAGKgvV6iimEe4sAyyncj2eoX0duAm/rkXFk65JrDRy3gMJrc3o9dSH8r3Nk2b4Qgf0amk8bQJHIB8yUZq2CzqJparxU9t5kJHuNH1DQ+NtoglCsu8ff7WTXUtUUI/Cj00KiKdEVS16VWOwJBVLlpCzzcODJOxqNnyc2dK2JcSxuRjw9r/+s5Y5XjKaPoS6uBtCbzPKaBPvirYuKO+AtAoFYNNrdvZahnBfoLR5M/qA+3YkO5BCY03/VtaPD+Id/qqS53+b0ehvaRsKH8CZDgrdGS3BI+2wbrHNWwEv4N+g5tyUpXwc8btEnATsSpDZXftrTatJUt1GSfEh++zg3uV98oPqqlDANaNRGWR4wh/m9cZ7a6oISotHnAwmOHHAKtk+aXG3Przak7du8dJUVFRHh8N39f5PIYI187DEiOTlKMVgK4lDT8Tqv6hYBevP157ibGwjnp8gA+Qj6T7bPwP6K7jNQL6yE+byptuHWvw8y6D+tMbenzjym1WkKqbYTBatIHlHfaGm/KvYIXrQFPsaK+PcrB68pPJRPW81Ns+iIYQqB9xnp8mtv7rMmqcG9KjBuXuxw529TRxvQceU69LTf3AZYq8Yi7lf0ufQsnJMJXG5C9LWoHp62u2ry/ewvL+6CD4c+FOMQX8MTXgRo=
deploy:
- provider: npm
  api_key:
    secure: x2h+y2/Fzjp45tNGTLEK62FlEQmiCneJZ6CKPPHryWzq0FP4CPawbKxFW1SgKsqpWsGUvq6gTI5QWzHqnkD+PremXRM7MjKCq/BBUfoW4Gsd94VG96mJdPo6BXGivqrcaL8iatFKjt2Y5OC0SGPVG2+ZzWQj2OfGlLHhaPt/JqpMnyu3tvDcJ0O9aAzEAxz6bhXELqOMjc6ZqssfBy5txbZOATodKd0PVwWJIPhnq9saW6REX0H2ssL3Cycv0+R2zQG/DTSmxLJS8SeVCUUuL3pJO0e+C8QqWTNkZw5aO1oVUsXI+fufi2rfHmzjl0fN/hzoLKocO5MV9fePbCQeFWgxfpNC5q1+yl0giNd8t5h7CMwMygh/19BVxiuV4O9HfXzoFfA2hT2NArBPj9WhJ3TxdmXnieLCntv+geQI0v4kCnaecDQIdRK0OtOro8jYJX7AVHQJzXJY5XI81jOdy3kpwW0wUgXzrBT6/AZg5QTVrp+D8Ug5XJB8l+w6rUjINElrw4ZAqOQkUrQves+exk+bO3KeFAPf8QdNLdhMA5BsEOxcw0lw0QPsRFeuEl23n4Gicuzd/y7n/7Jepmj/hQiCz9NWN0LNSQP/6VKzlySoBvEAvGnCzmrrDrJtwDw/WbJp1bf6TmI56UicUTg3UILMAMGZytIt6pubI5PSr28=
  email:
    secure: mV1Z31ULxfyy2AcZnlvw1KJsaDCUMSBobHtkdvIEVp1/SxMwWAIf6eEFwLkM7XMBD4C7J16y7V01KWDwoxnQ64q5JeVRH2+/KDXDFxHhwp1xNwNZNC2B1WvQVchLK90YHQ+h/lcLgNQE+ygzzjgX406zkyk3J7Aqx75u36gN8Wmnrxfaws0TeBFOOxEaW4hpNeZPkf67680gxGZjX0s/1HXhNXdcMYZWyR6aeSoTrdG1F2JRA74dHW00ijRvtobqP1KkdiQYVctsGFMr/VpHKg4YT3t4M7XGbHk+vRIaDYHzZ76p7xPcUwnxjRfK4iyn953+JtLbQgufQDz9bXSGFXUd6D/Gxag/wI3ONG3StUtfeCfXQQ/CIkzn1+PmxtGCiUIl38qY/Ocm4NEPDry9fVuw7Rq/ULy50k1/QSMhyu+oMILzRiHXCG8EM8RjXs9lB+Z3zcNWRPIE0DxQnfJzhj0ChYxnuj7zunGtHrbLIK7+oYdY0EYT2WlugeyaatRNX5sYXWXPcOK1JJYKKHt5Y3NG+jpnjHJCPsPnujYrGLh3kGzYjWIxvFE4CF+ckiX4NXJqKYzFXyK4q7OycLWnndu2WSaKcY4Lck/7SYlw4/QXOHM0NW8xxJALFuzKJDgnkLflrHtZq2JUL2qwjQmi+ZLXB/Ol4H1NCmYAXqIhH0g=
  on:
    branch: master
